# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 15:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='', max_length=100)),
                ('year', models.IntegerField(default=0)),
                ('major', models.CharField(default='', max_length=100)),
                ('member_status', models.IntegerField(verbose_name=0)),
                ('address', models.TextField(default='')),
                ('initiation_date', models.DateField(null=True)),
                ('emergency_contact', models.TextField(default='')),
                ('student_orgs', models.TextField(default='')),
                ('allergies', models.TextField(default='')),
                ('interests', models.TextField(default='')),
                ('parents_address', models.TextField(verbose_name='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
