# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle_website.auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brother',
            name='tshirt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brother',
            name='member_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brother',
            name='parents_address',
            field=models.TextField(default=''),
        ),
    ]
