# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle_website.auth', '0002_auto_20160214_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='member_status',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Pledge'), (2, 'Active')], default=0),
        ),
        migrations.AlterField(
            model_name='brother',
            name='parents_address',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='brother',
            name='tshirt',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL'), (5, 'XXL'), (6, 'XXXL')], default=0),
        ),
        migrations.AlterField(
            model_name='brother',
            name='year',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Freshman'), (2, 'Sophomore'), (3, 'Junior'), (5, 'Alumnus')], default=0),
        ),
    ]
