# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle_website.auth', '0004_brother_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='parents_address',
            field=models.TextField(default=''),
        ),
    ]
