# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle_website.auth', '0005_auto_20160214_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='allergies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='brother',
            name='interests',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='brother',
            name='parents_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='brother',
            name='position',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='brother',
            name='student_orgs',
            field=models.TextField(blank=True, default=''),
        ),
    ]
