# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle_website.auth', '0006_auto_20160214_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='year',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Freshman'), (2, 'Sophomore'), (3, 'Junior'), (4, 'Senior'), (5, 'Alumnus')], default=0),
        ),
    ]
