# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle_website.auth', '0008_auto_20160214_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='member_status',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Pledge'), (2, 'Active'), (3, 'Alumni')], default=0),
        ),
    ]
