# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='name',
            new_name='text',
        ),
    ]
