# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 02:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_election_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
