# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_auto_20160103_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='id',
        ),
        migrations.AddField(
            model_name='voter',
            name='id1',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
