# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_auto_20160213_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='uuid',
        ),
        migrations.AddField(
            model_name='voter',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
