# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passcode',
            name='election',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voting.Election'),
        ),
    ]
